# -*- coding: utf-8 -*-
"""Visão Computacional (Syngenta) Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvnH9AAkBo76m56HdPE2AFIMWslQUKx5

# **IMPORTAÇÃO DE BIBLIOTECAS E CONFIGURAÇÃO**
"""

import os
import random
import kagglehub
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model

EXIBIR_LOGS = True
FORCAR_RETREINAMENTO = False

if EXIBIR_LOGS:
    print("Inicializando pipeline de visão computacional aplicada à fitopatologia.")

"""# **DOWNLOAD DO DATASET**"""

if EXIBIR_LOGS:
    print("Verificando integridade e baixando o dataset de imagens...")

path = kagglehub.dataset_download("emmarex/plantdisease")

if EXIBIR_LOGS:
    print(f"Dataset disponível no diretório: {path}")

"""# **EXTRAÇÃO DE SEVERIDADE**"""

def extrair_severidade_foliar(caminho_imagem):
    """
    Segmenta a folha e a lesão usando espaço de cores HSV para calcular a área afetada.
    """
    if EXIBIR_LOGS:
        print(f"Processando imagem para segmentação fenotípica: {caminho_imagem}")

    imagem = cv2.imread(caminho_imagem)
    if imagem is None:
        if EXIBIR_LOGS:
            print("Falha ao carregar a imagem. Verifique o caminho do arquivo.")
        return None

    hsv = cv2.cvtColor(imagem, cv2.COLOR_BGR2HSV)

    baixo_verde = np.array([25, 40, 40])
    alto_verde = np.array([90, 255, 255])

    baixo_doenca = np.array([10, 50, 20])
    alto_doenca = np.array([24, 255, 255])

    mascara_verde = cv2.inRange(hsv, baixo_verde, alto_verde)
    mascara_doenca = cv2.inRange(hsv, baixo_doenca, alto_doenca)

    pixels_saudaveis = cv2.countNonZero(mascara_verde)
    pixels_doentes = cv2.countNonZero(mascara_doenca)
    pixels_totais_tecido = pixels_saudaveis + pixels_doentes

    severidade = (pixels_doentes / pixels_totais_tecido) * 100 if pixels_totais_tecido > 0 else 0

    if EXIBIR_LOGS:
        print(f"Área verde saudável: {pixels_saudaveis} pixels")
        print(f"Área lesionada: {pixels_doentes} pixels")
        print(f"Severidade calculada: {severidade:.2f}% de área afetada")

    return severidade, mascara_verde, mascara_doenca

"""# **IMAGEM DE TESTE**"""

if EXIBIR_LOGS:
    print("Preparando o ambiente gráfico para validação visual...")

caminho_imagem_teste = None
for raiz, diretorios, arquivos in os.walk(path):
    for arquivo in arquivos:
        if arquivo.lower().endswith(('.png', '.jpg', '.jpeg')):
            caminho_imagem_teste = os.path.join(raiz, arquivo)
            break
    if caminho_imagem_teste:
        break

if caminho_imagem_teste is None:
    if EXIBIR_LOGS:
        print("Nenhuma imagem encontrada no diretório baixado.")
else:
    if EXIBIR_LOGS:
        print(f"Imagem selecionada para visualização: {caminho_imagem_teste}")

"""# **SEGMENTAÇÃO**"""

if caminho_imagem_teste is not None:
    resultado = extrair_severidade_foliar(caminho_imagem_teste)

    if resultado is not None:
        severidade, mascara_verde, mascara_doenca = resultado

        imagem_original = cv2.imread(caminho_imagem_teste)
        imagem_rgb = cv2.cvtColor(imagem_original, cv2.COLOR_BGR2RGB)

        if EXIBIR_LOGS:
            print("Montando os painéis de visualização dos tecidos vegetais...")

        figura, eixos = plt.subplots(1, 3, figsize=(15, 5))

        eixos[0].imshow(imagem_rgb)
        eixos[0].set_title('Folha Original (In Vivo)')
        eixos[0].axis('off')

        eixos[1].imshow(mascara_verde, cmap='gray')
        eixos[1].set_title('Máscara: Tecido Saudável')
        eixos[1].axis('off')

        eixos[2].imshow(mascara_doenca, cmap='gray')
        eixos[2].set_title(f'Máscara: Lesão ({severidade:.1f}%)')
        eixos[2].axis('off')

        plt.tight_layout()
        plt.show()

"""# **PREPARAÇÃO DOS DADOS PARA DEEP LEARNING**"""

if EXIBIR_LOGS:
    print("Iniciando a etapa de Transfer Learning e mapeamento de diretórios...")

caminho_base = path
for raiz, diretorios, arquivos in os.walk(path):
    if len(diretorios) > 10:
        caminho_base = raiz
        break

if EXIBIR_LOGS:
    print(f"Diretório base de imagens identificado: {caminho_base}")
    print("Carregando e dividindo pacotes de treino e validação...")

tamanho_lote = 32
tamanho_imagem = (224, 224)

dataset_treino = tf.keras.utils.image_dataset_from_directory(
    caminho_base,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=tamanho_imagem,
    batch_size=tamanho_lote
)

dataset_validacao = tf.keras.utils.image_dataset_from_directory(
    caminho_base,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=tamanho_imagem,
    batch_size=tamanho_lote
)

nomes_classes = dataset_treino.class_names
numero_classes = len(nomes_classes)

if EXIBIR_LOGS:
    print(f"{numero_classes} classes de patógenos mapeadas com sucesso.")

"""# **MODELO DEEP LEARNING (TRANSFER LEARNING)**"""

NOME_ARQUIVO_MODELO = 'modelo_fitopatologia_treinado.keras'

if os.path.exists(NOME_ARQUIVO_MODELO) and not FORCAR_RETREINAMENTO:
    if EXIBIR_LOGS:
        print(f"Modelo pré-treinado localizado. Carregando pesos e arquitetura de: {NOME_ARQUIVO_MODELO}")
    
    modelo_fitopatologia = tf.keras.models.load_model(NOME_ARQUIVO_MODELO)
else:
    if EXIBIR_LOGS:
        print("Modelo persistido não encontrado. Iniciando construção e treinamento ...")

    aumento_dados = tf.keras.Sequential([
        tf.keras.layers.RandomFlip("horizontal_and_vertical"),
        tf.keras.layers.RandomRotation(0.2),
    ])    

    modelo_base = MobileNetV2(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet'
    )

    modelo_base.trainable = False

    entradas = tf.keras.Input(shape=(224, 224, 3))
    x = aumento_dados(entradas)
    x = tf.keras.applications.mobilenet_v2.preprocess_input(x)
    x = modelo_base(x, training=False)
    x = GlobalAveragePooling2D()(x)
    saidas = Dense(numero_classes, activation='softmax')(x)

    modelo_fitopatologia = Model(entradas, saidas)

    modelo_fitopatologia.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    historico = modelo_fitopatologia.fit(
        dataset_treino,
        validation_data=dataset_validacao,
        epochs=12
    )

    modelo_fitopatologia.save(NOME_ARQUIVO_MODELO)
    
    if EXIBIR_LOGS:
        print(f"Fase de aprendizado concluída. Modelo exportado com sucesso para: {NOME_ARQUIVO_MODELO}")

"""# **CLASSIFICAÇÃO PREDITIVA**"""

def classificar_patogeno(caminho_img, modelo, classes):
    if EXIBIR_LOGS:
        print(f"Adaptando a imagem para os padrões da rede: {caminho_img}")

    img = tf.keras.utils.load_img(caminho_img, target_size=(224, 224))
    img_array = tf.keras.utils.img_to_array(img)
    img_lote = np.expand_dims(img_array, axis=0)

    predicoes = modelo.predict(img_lote, verbose=0)

    indice_predicao = np.argmax(predicoes[0])
    classe_original = classes[indice_predicao].lower()

    cultura = "Desconhecida"
    if "pepper" in classe_original:
        cultura = "Pimentão"
    elif "potato" in classe_original:
        cultura = "Batata"
    elif "tomato" in classe_original:
        cultura = "Tomate"

    diagnostico = "Não Identificado"
    if "healthy" in classe_original:
        diagnostico = "Saudável"
    elif "bacterial" in classe_original:
        diagnostico = "Mancha Bacteriana"
    elif "early" in classe_original:
        diagnostico = "Pinta Preta"
    elif "late" in classe_original:
        diagnostico = "Requeima"
    elif "mold" in classe_original:
        diagnostico = "Bolor Foliar"
    elif "septoria" in classe_original:
        diagnostico = "Mancha de Septoria"
    elif "mite" in classe_original or "spider" in classe_original:
        diagnostico = "Ácaro Rajado"
    elif "target" in classe_original:
        diagnostico = "Mancha Alvo"
    elif "yellow" in classe_original or "curl" in classe_original:
        diagnostico = "Vírus do Mosaico Amarelo"
    elif "mosaic" in classe_original:
        diagnostico = "Vírus do Mosaico"
    else:
        diagnostico = classe_original.replace('_', ' ').title()

    classe_traduzida = f"Cultura: {cultura} | Patógeno: {diagnostico}"
    confianca = predicoes[0][indice_predicao] * 100

    return classe_traduzida, confianca

"""# **TESTE DE PREDIÇÃO**"""

if EXIBIR_LOGS:
    print("Iniciando a etapa de inferência preditiva isolada...")

if caminho_imagem_teste is not None:
    diagnostico, precisao = classificar_patogeno(caminho_imagem_teste, modelo_fitopatologia, nomes_classes)

    if EXIBIR_LOGS:
        print("Diagnóstico concluído!")
        print(f"Patógeno/Condição Identificada: {diagnostico}")
        print(f"Nível de Confiança: {precisao:.2f}%")
else:
    if EXIBIR_LOGS:
        print("Nenhuma imagem de teste disponível para a inferência.")

"""# **PROCESSAMENTO EM LOTE**"""

if EXIBIR_LOGS:
    print("Iniciando o processamento em lote para avaliação de múltiplas amostras...")

todas_imagens = []
for raiz, diretorios, arquivos in os.walk(path):
    for arquivo in arquivos:
        if arquivo.lower().endswith(('.png', '.jpg', '.jpeg')):
            todas_imagens.append(os.path.join(raiz, arquivo))

amostras_selecionadas = random.sample(todas_imagens, min(4, len(todas_imagens)))

if EXIBIR_LOGS:
    print(f"{len(amostras_selecionadas)} amostras selecionadas para a composição do painel.")

figura, eixos = plt.subplots(len(amostras_selecionadas), 2, figsize=(10, 4 * len(amostras_selecionadas)))

if len(amostras_selecionadas) == 1:
    eixos = [eixos]

for i, caminho_amostra in enumerate(amostras_selecionadas):
    if EXIBIR_LOGS:
        print(f"Analisando amostra {i+1}/{len(amostras_selecionadas)}...")

    resultado_cv = extrair_severidade_foliar(caminho_amostra)
    if resultado_cv is None:
        continue

    severidade, mascara_verde, mascara_doenca = resultado_cv
    diagnostico, confianca = classificar_patogeno(caminho_amostra, modelo_fitopatologia, nomes_classes)

    img_original = cv2.imread(caminho_amostra)
    img_rgb = cv2.cvtColor(img_original, cv2.COLOR_BGR2RGB)

    eixos[i][0].imshow(img_rgb)
    eixos[i][0].set_title(f'{diagnostico}\nConfiança IA: {confianca:.1f}%', fontsize=10)
    eixos[i][0].axis('off')

    eixos[i][1].imshow(mascara_doenca, cmap='gray')
    eixos[i][1].set_title(f'Segmentação da Lesão\nSeveridade (Área Afetada): {severidade:.2f}%', fontsize=10)
    eixos[i][1].axis('off')

plt.tight_layout()
plt.show()
